### ISSUE TITLE
Unable to successfully import as of Omeka S 0.8.2-alpha

### ISSUE THREAD

**Issue by kimisgold** [omeka-s-modules/Omeka2Importer#71]
I have tried importing using the following endpoints:

- http://physical-electrical-digital.nyufasedtech.com/api
- http://mallhistory.org/api

The jobs start, but never import items or provide a way to stop the jobs. They also provide no logs. Here are the arguments passed to the first job:

```

{
    "endpoint": "http:\/\/physical-electrical-digital.nyufasedtech.com\/api",
    "key": "http:\/\/physical-electrical-digital.nyufasedtech.com\/api",
    "comment": "",
    "itemSet": "1",
    "importCollections": "1",
    "csrf": "57782ee389ba5aa58f1ab5c3049c2cb9-ba44668a6beba5b25e9b9967d23b8e5b",
    "element-property": {
        "37": [
            "6"
        ],
        "38": [
            "14"
        ],
        "39": [
            "2"
        ],
        "40": [
            "7"
        ],
        "41": [
            "4"
        ],
        "42": [
            "9"
        ],
        "43": [
            "10"
        ],
        "44": [
            "12"
        ],
        "45": [
            "5"
        ],
        "46": [
            "13"
        ],
        "47": [
            "15"
        ],
        "48": [
            "11"
        ],
        "49": [
            "3"
        ],
        "50": [
            "1"
        ],
        "51": [
            "8"
        ],
        "2": [
            "69"
        ],
        "3": [
            "68"
        ],
        "7": [
            "9"
        ],
        "10": [
            "25"
        ],
        "11": [
            "25"
        ],
        "13": [
            "76"
        ],
        "14": [
            "64"
        ],
        "19": [
            "76"
        ],
        "20": [
            "77"
        ],
        "21": [
            "77"
        ]
    },
    "type-class": {
        "8": "25"
    }
}
```

**Comment by patrickmj** [comment]
Anything in the logs? My imports from those sites are coming in okay.

**Comment by kimisgold** [comment]
They weren't producing logs, but I upgraded my version of PHP (from 5.4 to 5.6) and I got the following:

```
2016-09-30T19:49:51+00:00 DEBUG (7): Importing item page 1
2016-09-30T19:50:02+00:00 ERR (3): exception 'Omeka\File\Exception\InvalidThumbnailerException' with message 'ImageMagick error: invalid ImageMagick command.' in /Users/kim/Sites/omeka-s/application/src/File/Thumbnailer/ImageMagickThumbnailer.php:102
Stack trace:
#0 /Users/kim/Sites/omeka-s/application/src/File/Thumbnailer/ImageMagickThumbnailer.php(37): Omeka\File\Thumbnailer\ImageMagickThumbnailer->setConvertPath('/opt/local/bin')
#1 /Users/kim/Sites/omeka-s/application/src/File/Manager.php(127): Omeka\File\Thumbnailer\ImageMagickThumbnailer->setOptions(Array)
#2 /Users/kim/Sites/omeka-s/application/src/Media/Ingester/Url.php(81): Omeka\File\Manager->storeThumbnails(Object(Omeka\File\File))
#3 /Users/kim/Sites/omeka-s/application/src/Api/Adapter/MediaAdapter.php(154): Omeka\Media\Ingester\Url->ingest(Object(Omeka\Entity\Media), Object(Omeka\Api\Request), Object(Omeka\Stdlib\ErrorStore))
#4 /Users/kim/Sites/omeka-s/application/src/Api/Adapter/AbstractEntityAdapter.php(418): Omeka\Api\Adapter\MediaAdapter->hydrate(Object(Omeka\Api\Request), Object(Omeka\Entity\Media), Object(Omeka\Stdlib\ErrorStore))
#5 /Users/kim/Sites/omeka-s/application/src/Api/Adapter/ItemAdapter.php(206): Omeka\Api\Adapter\AbstractEntityAdapter->hydrateEntity(Object(Omeka\Api\Request), Object(Omeka\Entity\Media), Object(Omeka\Stdlib\ErrorStore))
#6 /Users/kim/Sites/omeka-s/application/src/Api/Adapter/AbstractEntityAdapter.php(418): Omeka\Api\Adapter\ItemAdapter->hydrate(Object(Omeka\Api\Request), Object(Omeka\Entity\Item), Object(Omeka\Stdlib\ErrorStore))
#7 /Users/kim/Sites/omeka-s/application/src/Api/Adapter/AbstractEntityAdapter.php(286): Omeka\Api\Adapter\AbstractEntityAdapter->hydrateEntity(Object(Omeka\Api\Request), Object(Omeka\Entity\Item), Object(Omeka\Stdlib\ErrorStore))
#8 /Users/kim/Sites/omeka-s/application/src/Api/Manager.php(341): Omeka\Api\Adapter\AbstractEntityAdapter->batchCreate(Object(Omeka\Api\Request))
#9 /Users/kim/Sites/omeka-s/application/src/Api/Manager.php(215): Omeka\Api\Manager->executeBatchCreate(Object(Omeka\Api\Request), Object(Omeka\Api\Adapter\ItemAdapter))
#10 /Users/kim/Sites/omeka-s/application/src/Api/Manager.php(92): Omeka\Api\Manager->execute(Object(Omeka\Api\Request))
#11 /Users/kim/Sites/omeka-s/modules/Omeka2Importer/src/Job/Import.php(224): Omeka\Api\Manager->batchCreate('items', Array, Array, true)
#12 /Users/kim/Sites/omeka-s/modules/Omeka2Importer/src/Job/Import.php(208): Omeka2Importer\Job\Import->createItems(Array)
#13 /Users/kim/Sites/omeka-s/modules/Omeka2Importer/src/Job/Import.php(77): Omeka2Importer\Job\Import->importItems(Array)
#14 /Users/kim/Sites/omeka-s/application/src/Job/Strategy/SynchronousStrategy.php(37): Omeka2Importer\Job\Import->perform()
#15 /Users/kim/Sites/omeka-s/application/src/Job/Dispatcher.php(105): Omeka\Job\Strategy\SynchronousStrategy->send(Object(Omeka\Entity\Job))
#16 /Users/kim/Sites/omeka-s/application/data/scripts/perform-job.php(43): Omeka\Job\Dispatcher->send(Object(Omeka\Entity\Job), Object(Omeka\Job\Strategy\SynchronousStrategy))
```

And pretty much a similar block for all the subsequent item import attempts.

**Comment by kimisgold** [comment]
Turns out it was an incorrect ImageMagick path.
