### ISSUE TITLE
FK violation when deleting an imported item set

### ISSUE THREAD

**Issue by patrickmj** [omeka-s-modules/Omeka2Importer#80]
```
PDOException: SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`omeka3`.`omekaimport_record`, CONSTRAINT `FK_3185E9B1960278D7` FOREIGN KEY (`item_set_id`) REFERENCES `item_set` (`id`)) in /var/www/omekas/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91
Stack trace:
#0 /var/www/omekas/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(91): PDOStatement->execute(Array)
#1 /var/www/omekas/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(989): Doctrine\DBAL\Driver\PDOStatement->execute(Array)
#2 /var/www/omekas/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(594): Doctrine\DBAL\Connection->executeUpdate('DELETE FROM res...', Array, Array)
#3 /var/www/omekas/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/JoinedSubclassPersister.php(285): Doctrine\DBAL\Connection->delete('resource', Array)
#4 /var/www/omekas/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(1098): Doctrine\ORM\Persisters\Entity\JoinedSubclassPersister->delete(Object(Omeka\Entity\ItemSet))
#5 /var/www/omekas/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(406): Doctrine\ORM\UnitOfWork->executeDeletions(Object(Doctrine\ORM\Mapping\ClassMetadata))
#6 /var/www/omekas/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(356): Doctrine\ORM\UnitOfWork->commit(NULL)
#7 /var/www/omekas/application/src/Api/Adapter/AbstractEntityAdapter.php(345): Doctrine\ORM\EntityManager->flush()
#8 /var/www/omekas/application/src/Api/Manager.php(227): Omeka\Api\Adapter\AbstractEntityAdapter->delete(Object(Omeka\Api\Request))
#9 /var/www/omekas/application/src/Api/Manager.php(145): Omeka\Api\Manager->execute(Object(Omeka\Api\Request))
#10 /var/www/omekas/application/src/Mvc/Controller/Plugin/Api.php(147): Omeka\Api\Manager->delete('item_sets', '2026', Array)
#11 /var/www/omekas/application/src/Controller/Admin/ItemSetController.php(153): Omeka\Mvc\Controller\Plugin\Api->delete('item_sets', '2026')
#12 /var/www/omekas/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(78): Omeka\Controller\Admin\ItemSetController->deleteAction()
#13 /var/www/omekas/vendor/zendframework/zend-eventmanager/src/EventManager.php(271): Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#14 /var/www/omekas/vendor/zendframework/zend-eventmanager/src/EventManager.php(151): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent), Object(Closure))
#15 /var/www/omekas/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(105): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#16 /var/www/omekas/vendor/zendframework/zend-mvc/src/DispatchListener.php(119): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#17 /var/www/omekas/vendor/zendframework/zend-eventmanager/src/EventManager.php(271): Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#18 /var/www/omekas/vendor/zendframework/zend-eventmanager/src/EventManager.php(151): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent), Object(Closure))
#19 /var/www/omekas/vendor/zendframework/zend-mvc/src/Application.php(332): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#20 /var/www/omekas/index.php(17): Zend\Mvc\Application->run()
#21 {main}

Next Doctrine\DBAL\Driver\PDOException: SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`omeka3`.`omekaimport_record`, CONSTRAINT `FK_3185E9B1960278D7` FOREIGN KEY (`item_set_id`) REFERENCES `item_set` (`id`)) in /var/www/omekas/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93
Stack trace:
#0 /var/www/omekas/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(989): Doctrine\DBAL\Driver\PDOStatement->execute(Array)
#1 /var/www/omekas/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(594): Doctrine\DBAL\Connection->executeUpdate('DELETE FROM res...', Array, Array)
#2 /var/www/omekas/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/JoinedSubclassPersister.php(285): Doctrine\DBAL\Connection->delete('resource', Array)
#3 /var/www/omekas/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(1098): Doctrine\ORM\Persisters\Entity\JoinedSubclassPersister->delete(Object(Omeka\Entity\ItemSet))
#4 /var/www/omekas/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(406): Doctrine\ORM\UnitOfWork->executeDeletions(Object(Doctrine\ORM\Mapping\ClassMetadata))
#5 /var/www/omekas/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(356): Doctrine\ORM\UnitOfWork->commit(NULL)
#6 /var/www/omekas/application/src/Api/Adapter/AbstractEntityAdapter.php(345): Doctrine\ORM\EntityManager->flush()
#7 /var/www/omekas/application/src/Api/Manager.php(227): Omeka\Api\Adapter\AbstractEntityAdapter->delete(Object(Omeka\Api\Request))
#8 /var/www/omekas/application/src/Api/Manager.php(145): Omeka\Api\Manager->execute(Object(Omeka\Api\Request))
#9 /var/www/omekas/application/src/Mvc/Controller/Plugin/Api.php(147): Omeka\Api\Manager->delete('item_sets', '2026', Array)
#10 /var/www/omekas/application/src/Controller/Admin/ItemSetController.php(153): Omeka\Mvc\Controller\Plugin\Api->delete('item_sets', '2026')
#11 /var/www/omekas/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(78): Omeka\Controller\Admin\ItemSetController->deleteAction()
#12 /var/www/omekas/vendor/zendframework/zend-eventmanager/src/EventManager.php(271): Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#13 /var/www/omekas/vendor/zendframework/zend-eventmanager/src/EventManager.php(151): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent), Object(Closure))
#14 /var/www/omekas/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(105): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#15 /var/www/omekas/vendor/zendframework/zend-mvc/src/DispatchListener.php(119): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#16 /var/www/omekas/vendor/zendframework/zend-eventmanager/src/EventManager.php(271): Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#17 /var/www/omekas/vendor/zendframework/zend-eventmanager/src/EventManager.php(151): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent), Object(Closure))
#18 /var/www/omekas/vendor/zendframework/zend-mvc/src/Application.php(332): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#19 /var/www/omekas/index.php(17): Zend\Mvc\Application->run()
#20 {main}

Next Doctrine\DBAL\Exception\ForeignKeyConstraintViolationException: An exception occurred while executing 'DELETE FROM resource WHERE id = ?' with params [2026]:

SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`omeka3`.`omekaimport_record`, CONSTRAINT `FK_3185E9B1960278D7` FOREIGN KEY (`item_set_id`) REFERENCES `item_set` (`id`)) in /var/www/omekas/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:60
Stack trace:
#0 /var/www/omekas/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(116): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException))
#1 /var/www/omekas/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(996): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'DELETE FROM res...', Array)
#2 /var/www/omekas/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(594): Doctrine\DBAL\Connection->executeUpdate('DELETE FROM res...', Array, Array)
#3 /var/www/omekas/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/JoinedSubclassPersister.php(285): Doctrine\DBAL\Connection->delete('resource', Array)
#4 /var/www/omekas/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(1098): Doctrine\ORM\Persisters\Entity\JoinedSubclassPersister->delete(Object(Omeka\Entity\ItemSet))
#5 /var/www/omekas/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(406): Doctrine\ORM\UnitOfWork->executeDeletions(Object(Doctrine\ORM\Mapping\ClassMetadata))
#6 /var/www/omekas/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(356): Doctrine\ORM\UnitOfWork->commit(NULL)
#7 /var/www/omekas/application/src/Api/Adapter/AbstractEntityAdapter.php(345): Doctrine\ORM\EntityManager->flush()
#8 /var/www/omekas/application/src/Api/Manager.php(227): Omeka\Api\Adapter\AbstractEntityAdapter->delete(Object(Omeka\Api\Request))
#9 /var/www/omekas/application/src/Api/Manager.php(145): Omeka\Api\Manager->execute(Object(Omeka\Api\Request))
#10 /var/www/omekas/application/src/Mvc/Controller/Plugin/Api.php(147): Omeka\Api\Manager->delete('item_sets', '2026', Array)
#11 /var/www/omekas/application/src/Controller/Admin/ItemSetController.php(153): Omeka\Mvc\Controller\Plugin\Api->delete('item_sets', '2026')
#12 /var/www/omekas/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(78): Omeka\Controller\Admin\ItemSetController->deleteAction()
#13 /var/www/omekas/vendor/zendframework/zend-eventmanager/src/EventManager.php(271): Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#14 /var/www/omekas/vendor/zendframework/zend-eventmanager/src/EventManager.php(151): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent), Object(Closure))
#15 /var/www/omekas/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(105): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#16 /var/www/omekas/vendor/zendframework/zend-mvc/src/DispatchListener.php(119): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#17 /var/www/omekas/vendor/zendframework/zend-eventmanager/src/EventManager.php(271): Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#18 /var/www/omekas/vendor/zendframework/zend-eventmanager/src/EventManager.php(151): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent), Object(Closure))
#19 /var/www/omekas/vendor/zendframework/zend-mvc/src/Application.php(332): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#20 /var/www/omekas/index.php(17): Zend\Mvc\Application->run()
#21 {main}
```

**Comment by patrickmj** [comment]
Looks like it just needs the `api.delete.pre` event to delete the import record

**Comment by zerocrates** [comment]
Probably simplest to just set ON DELETE CASCADE for the omekaimport_record item_set_id column. Looks like you already have this for the item column.
