### ISSUE TITLE
Exception on importing an item from Sandbox

### ISSUE THREAD

**Issue by patrickmj** [omeka-s-modules/Omeka2Importer#88]
Reproduced it once, but currently not able to again reproduce https://github.com/omeka-s-modules/Omeka2Importer/issues/81#issuecomment-261048998

But while trying got this.

Importing from dev.omeka.org/mebrett/Omeka

Been undoing every import before the next try.

It looks like there might be a quirk with one item that doesn't make the process completely collapse on page 2, but tracking it down is. . . tricky.

```
2016-11-18T18:21:17+00:00 INFO (6): Importing item page 1
2016-11-18T18:22:36+00:00 INFO (6): Importing item page 2
2016-11-18T18:24:08+00:00 ERR (3): exception 'Omeka\Api\Exception\ValidationException' in /var/www/omekas/application/src/Api/Adapter/AbstractEntityAdapter.php:437
Errors:
{
    "o:media": [
        {
            "upload": [
                {}
            ]
        }
    ]
}
Stack trace:
#0 /var/www/omekas/application/src/Api/Adapter/AbstractEntityAdapter.php(286): Omeka\Api\Adapter\AbstractEntityAdapter->hydrateEntity(Object(Omeka\Api\Request), Object(Omeka\Entity\Item), Object(Omeka\Stdlib\ErrorStore))
#1 /var/www/omekas/application/src/Api/Manager.php(344): Omeka\Api\Adapter\AbstractEntityAdapter->batchCreate(Object(Omeka\Api\Request))
#2 /var/www/omekas/application/src/Api/Manager.php(218): Omeka\Api\Manager->executeBatchCreate(Object(Omeka\Api\Request), Object(Omeka\Api\Adapter\ItemAdapter))
#3 /var/www/omekas/application/src/Api/Manager.php(92): Omeka\Api\Manager->execute(Object(Omeka\Api\Request))
#4 /var/www/omekas/modules/Omeka2Importer/src/Job/Import.php(234): Omeka\Api\Manager->batchCreate('items', Array, Array, true)
#5 /var/www/omekas/modules/Omeka2Importer/src/Job/Import.php(207): Omeka2Importer\Job\Import->createItems(Array)
#6 /var/www/omekas/modules/Omeka2Importer/src/Job/Import.php(79): Omeka2Importer\Job\Import->importItems(Array)
#7 /var/www/omekas/application/src/Job/Strategy/SynchronousStrategy.php(37): Omeka2Importer\Job\Import->perform()
#8 /var/www/omekas/application/src/Job/Dispatcher.php(105): Omeka\Job\Strategy\SynchronousStrategy->send(Object(Omeka\Entity\Job))
#9 /var/www/omekas/application/data/scripts/perform-job.php(43): Omeka\Job\Dispatcher->send(Object(Omeka\Entity\Job), Object(Omeka\Job\Strategy\SynchronousStrategy))
#10 {main}
```

**Comment by zerocrates** [comment]
Updating the core should make that message more actually of a message.

But it will be an error about MIME type or extension checking.

**Comment by patrickmj** [comment]
yep

```
2017-02-24T17:46:00+00:00 INFO (6): Importing item page 2
2017-02-24T17:48:42+00:00 ERR (3): exception 'Omeka\Api\Exception\ValidationException' in /var/www/html/omekas/application/src/Api/Adapter/AbstractEntityAdapter.php:441
Errors:
{
    "o:media": [
        {
            "upload": [
                "Error ingesting \"\/mebrett\/Omeka\/files\/original\/055c10c87c9fb0f79c43d194d28c52ec.m4a\". Cannot store files with the media type \"audio\/x-m4a\"."
            ]
        }
    ]
}

```

**Comment by patrickmj** [comment]
Possibly related, a fair amount of these

```
2017-02-24T18:12:12+00:00 ERR (3): Command "/usr/bin/convert '/tmp/omekaptw2P9[0]' -background white +repage -alpha remove -thumbnail '800x800>' '/tmp/omekauO6h5r.jpg'" failed with status code 1.
2017-02-24T18:13:48+00:00 ERR (3): Command "/usr/bin/convert '/tmp/omeka14cs8k[0]' -background white +repage -alpha remove -thumbnail '800x800>' '/tmp/omekasUn1rc.jpg'" failed with status code 1.
2017-02-24T18:13:59+00:00 ERR (3): Command "/usr/bin/convert '/tmp/omekaqFQ5Op[0]' -background white +repage -alpha remove -thumbnail '800x800>' '/tmp/omekaHNUDXM.jpg'" failed with status code 1.
2017-02-24T18:14:28+00:00 ERR (3): Command "/usr/bin/convert '/tmp/omeka0lMyPh[0]' -background white +repage -alpha remove -thumbnail '800x800>' '/tmp/omekaVhgJO3.jpg'" failed with status code 1.

```

**Comment by patrickmj** [comment]
ERRs from imagemagick look like unsurprising inability to create derivatives.

The bigger error in the log is definitely a MIME type not being in the whitelist. Checking the global settings to turn off validation makes it come in without error. Bonus -- doing the import without it checked, so that item fails, gives expected error message. Doing the import again with 'Update Previous Import' checked on the import settings, AND re-checking skip validation, makes the error disappear, and the import status says 1 created, and the rest updated. So so far, that looks like it's behaving as it should, and is just a thing to maybe document, or just be aware of when we respond to people with import issues. That's not much different from what we do now with Classic.
